variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  FEDORA_BUILD: openconnect-cli-fedora

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

MinGW32:
  script:
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - dnf -y install dnf-plugins-core
  - dnf -y copr enable dwmw2/openconnect
  - dnf -y install mingw32-openconnect mingw32-spdlog
  - mingw32-cmake .
  - make -j4
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bin/openconnect-gui.exe

MinGW64:
  script:
  - dnf remove -y wine.i686
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - dnf -y install dlugins-core
  - dnf -y copr enable dwmw2/openconnect
  - dnf -y install mingw64-openconnect mingw64-spdlog
  - mingw64-cmake .
  - make -j4
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bin/openconnect-gui.exe

