variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  FEDORA_BUILD: openconnect-cli-fedora39
  MINGW32_BUILD: openconnect-cli-mingw32
  MINGW64_BUILD: openconnect-cli-mingw64

Signoff:
  script:
  # Quoted to work around https://gitlab.com/gitlab-org/gitlab-foss/-/issues/20177
  - 'echo "Checking for new commits without Signed-off-by: tags as described in https://www.infradead.org/openconnect/contribute.html"'
  # Last bad commit
  - 'git log 7abb6359ce8be9952f768b643f96094e057f8a07.. --grep "(^Signed-off-by)|(^Merge branch)|(^This reverts commit)" --extended-regexp --invert-grep --exit-code'
  - echo "None (good)"

Fedora:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  script:
  - dnf -y install dnf-plugins-core qt5-qtbase-devel patch cmake spdlog-devel clang-tools-extra openconnect-devel
  - cmake .
  - make -j4
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bin/openconnect-gui

MinGW32:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$MINGW32_BUILD
  script:
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - dnf -y install dnf-plugins-core mingw32-qt5-qtbase patch
  - mingw32-cmake .
  - make -j4
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bin/openconnect-gui.exe

MinGW64:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$MINGW64_BUILD
  script:
  - dnf remove -y wine.i686
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - dnf -y install dnf-plugins-core mingw64-qt5-qtbase patch
  - mingw64-cmake .
  - make -j4
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bin/openconnect-gui.exe

.WindowsTemplate:
  tags:
  - shared-windows
  - windows
  - windows-1809
  script:
    - choco install msys2 patch qt5-default -y --no-progress
    - $Env:TARGET = "package"
    - $Env:GENERATOR = '"MinGW Makefiles"'
    - $Env:NSIS = 'C:\tools\msys64\mingw64\bin'
    - $Env:QT5 = 'C:\Qt\5.15.2\mingw81_64'
    - $Env:MINGW = 'C:\Qt\5.15.2\mingw81_64'
    - md -p build
    - cd build
    - $Env:PATH += "C:\tools\msys64\;C:\Program Files\Git\usr\bin;${Env:QT5}\bin;${Env:NSIS}"
    - cmd.exe /c c:\tools\msys64\msys2_shell.cmd -defterm -no-start -mingw64 -where ..\contrib\ -c "./build_mingw-openconnect@msys2.sh"
    - cmake -G "$Env:GENERATOR" -DCMAKE_BUILD_TYPE="$Env:BUILD_TYPE" ..
    - cmake --build . --config "$Env:BUILD_TYPE" --target "$Env:TARGET"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build/openconnect-gui*.exe
      - build/openconnect-gui*.exe.sha512

WindowsNative:
  extends: .WindowsTemplate
  variables:
    BUILD_TYPE: "Debug"
  except:
  - schedules
  - tags
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build/CMakeFiles/*.log

WindowsRelease:
  extends: .WindowsTemplate
  variables:
    BUILD_TYPE: "Release"
  only:
  - tags

