version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - gh-pages
image: Visual Studio 2019
clone_depth: 200
environment:
  QT5: C:\Qt\5.15.2\mingw81_64
  MINGW: C:\Qt\Tools\mingw810_64
  NSIS: C:\Program Files (x86)\NSIS
  matrix:
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Debug
    TARGET: package
#    TARGET: all
#  - GENERATOR: '"MinGW Makefiles"'
#    BUILD_TYPE: Release
#    TARGET: package
cache: .\build -> appveyor.yml
build_script:
- cmd: >-
    set

    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

    set PATH="%NSIS%";%PATH%

    if not exist build md build

    cd .\build

    c:\msys64\msys2_shell.cmd -defterm -no-start -mingw64 -where ..\contrib\ -c "./build_mingw-openconnect@msys2.sh"

    cmake -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

    cmake --build . --config %BUILD_TYPE% --target %TARGET%

    move /Y *.exe ..

    move /Y *.exe.sha512 ..

test: off
artifacts:
- path: openconnect-gui*.exe
  name: 'Installer'
- path: openconnect-gui*.exe.sha512
  name: 'Installer - sha512 hash'

